# It should be complemented by a samples.tsv file that contains one row per sample.

# -- Samples configuration -- #
samples: "samples.tsv"
out: "/data/gpfs-1/users/cofu10_c/scratch/P1812_SODAR/out"
log: "/data/gpfs-1/users/cofu10_c/scratch/P1812_SODAR/log" 

# -- Read input parameters -- #
input_dir: "/data/gpfs-1/groups/ag_ludwig/work/P1812_20221228/demuxed"
sample_id: "P1812"
file_types:
    - "fastq.gz"
    - "md5"

# -- Landing zone parameters -- #
landing_dir: "/data/gpfs-1/projects/ludwig_cubi/work"
sample_type: "Multiome-GEX" # choose between "Multiome-GEX", "scRNA-seq" #"multiome", "scATAC-seq" 
upload_to_sodar: false # Run upload script

# -- Resources configuration -- #
resources:
    default:
        threads: 1
        mem_mb: 8000
        walltime: 480
    landing:
        threads: 4
        mem_mb: 120000
        walltime: 1140
    upload:
        threads: 4
        mem_mb: 12000
        walltime: 1140

        